[package]
name = "aip-160"
version = "0.1.5"
description = "A Rust implementation of Google AIP-160 filtering standard."
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
default = []
sea-orm = ["dep:sea-orm"]

[dependencies]
pest = "2.7"
pest_derive = "2.7"
thiserror = "2.0"

sea-orm = { version = "1.1", features = ["sqlx-all"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
sea-orm = { version = "1.1", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
] }

[[example]]
name = "parser"

[[example]]
name = "sea_orm"
required-features = ["sea-orm"]
