[package]
name = "aip-193-derive"
version = "0.1.5"
description = "A Rust implementation of Google AIP-193 Errors derive macros."
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
proc-macro-crate = "2.0"

[dev-dependencies]
aip-193 = { path = "../aip-193", features = ["derive", "axum"] }
axum = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.26", features = ["derive"] }
