[package]
name = "aip-193"
version = "0.1.11"
description = "A Rust implementation of Google AIP-193 Errors."
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
default = []
derive = ["aip-193-derive"]

http = ["dep:http"]

axum = ["dep:axum-core", "dep:serde_json", "http"]

[dependencies]
aip-193-derive = { version = "0.1.7", path = "../aip-193-derive", optional = true }

http = { version = "1.0", optional = true }

axum-core = { version = "0.5", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
strum = { version = "0.26", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
http = "1.0"
